ecs_cluster_name = "albertleng-ecs-cluster-prod"
ecs_service_name = "albertleng-ecs-service-prod"
ecs_task_defn_family = "albertleng-ecs-task-def-prod"
ecs_container_name = "albertleng-container-prod"
ecs_port_name = "albertleng-3000-tcp-prod"